### ISSUE TITLE
Replace Developer Guide .png files with .svg format?

### ISSUE THREAD

**Issue by kevinswk94** [AY1920S2-CS2103T-W12-4/main#153]
Dear @okkhoy,

Are we allowed to switch to .svg files for our images? Will the bot be able to detect them and give us credit?

Thanks!

**Comment by kevinswk94** [comment]
adding @sharadhr , @AdarshChugani , @muhd97 and @e0316059 to the loop

**Comment by okkhoy** [comment]
Err...  bot checks for `png`
What be the problem with png?

**Comment by kevinswk94** [comment]
For the larger UML diagrams, the text becomes hard to read when zooming in due to the loss of quality. 

What if we maintain both `.png` and `.svg` files? Let the bot check `.png` while we link to the `.svg` in our guides?

**Comment by okkhoy** [comment]
> What if we maintain both .png and .svg files? Let the bot check .png while we link to the .svg in our guides?

Could be a work around. I hadn't thought of this 😂

**Comment by AdarshChugani** [comment]
Issue closed.

Will use both `png` and `svg` files for now.
